### ISSUE TITLE
如果某个用户被添加到多个机器人中，在其中某一个机器人中将该用户暂停会实现暂停效果吗？

### ISSUE THREAD

**Issue by pricalinat** [HenryzhaoH/bupt-ncov-report-tgbot#10]
如果某个用户被添加到多个机器人中，在其中某一个机器人中将该用户暂停会让其他机器人也暂停达到暂停效果吗？

**Comment by FredericDT** [comment]
在我们的实现中，不会。
我们定义“一个机器人”为一套完整的服务实例，每个实例之间不存在数据同步，则不能达成“在其中某一个机器人中将该用户暂停会让其他机器人也暂停达到暂停效果”。

**Comment by HenryzhaoH** [comment]
如果你是指的添加同一个学生信息到不同的TG用户中的话，不会。
每一个TG用户拥有的学生信息实例都是独立的，多个TG用户可以添加同一个学生用户，互不干扰。
